default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV["RAILS_DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  idle_timeout: <%= ENV["RAILS_IDLE_CONNECTION"] ||  60 %>
  port: <%= ENV['RAILS_DATABASE_PORT'] || 3000 %>
  host: localhost
  username: 'root'
  password: Root@123

development:
  <<: *default
  database: blog-article_development

test:
  <<: *default
  database: blog-article_test

production:
  <<: *default
  database: blog-article_production
